/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

import { Route as rootRouteImport } from './routes/__root'

const PhotographyLazyRouteImport = createFileRoute('/photography')()
const JouleHomeLazyRouteImport = createFileRoute('/joule-home')()
const FlowHomeLazyRouteImport = createFileRoute('/flow-home')()
const BiologyLazyRouteImport = createFileRoute('/biology')()
const IndexLazyRouteImport = createFileRoute('/')()
const JouleHomeIndexLazyRouteImport = createFileRoute('/joule-home/')()
const FlowHomeIndexLazyRouteImport = createFileRoute('/flow-home/')()
const JouleHomeEnergyUsageFormLazyRouteImport = createFileRoute(
  '/joule-home/energy-usage-form',
)()
const JouleHomeCurrentSystemLazyRouteImport = createFileRoute(
  '/joule-home/current-system',
)()
const JouleHomeAnalysisLazyRouteImport = createFileRoute(
  '/joule-home/analysis',
)()
const FlowHomeUsageLazyRouteImport = createFileRoute('/flow-home/usage')()
const FlowHomeProfileLazyRouteImport = createFileRoute('/flow-home/profile')()
const FlowHomeCostScheduleLazyRouteImport = createFileRoute(
  '/flow-home/cost-schedule',
)()

const PhotographyLazyRoute = PhotographyLazyRouteImport.update({
  id: '/photography',
  path: '/photography',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/photography.lazy').then((d) => d.Route))
const JouleHomeLazyRoute = JouleHomeLazyRouteImport.update({
  id: '/joule-home',
  path: '/joule-home',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/joule-home.lazy').then((d) => d.Route))
const FlowHomeLazyRoute = FlowHomeLazyRouteImport.update({
  id: '/flow-home',
  path: '/flow-home',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/flow-home.lazy').then((d) => d.Route))
const BiologyLazyRoute = BiologyLazyRouteImport.update({
  id: '/biology',
  path: '/biology',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/biology.lazy').then((d) => d.Route))
const IndexLazyRoute = IndexLazyRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/index.lazy').then((d) => d.Route))
const JouleHomeIndexLazyRoute = JouleHomeIndexLazyRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => JouleHomeLazyRoute,
} as any).lazy(() =>
  import('./routes/joule-home/index.lazy').then((d) => d.Route),
)
const FlowHomeIndexLazyRoute = FlowHomeIndexLazyRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => FlowHomeLazyRoute,
} as any).lazy(() =>
  import('./routes/flow-home/index.lazy').then((d) => d.Route),
)
const JouleHomeEnergyUsageFormLazyRoute =
  JouleHomeEnergyUsageFormLazyRouteImport.update({
    id: '/energy-usage-form',
    path: '/energy-usage-form',
    getParentRoute: () => JouleHomeLazyRoute,
  } as any).lazy(() =>
    import('./routes/joule-home/energy-usage-form.lazy').then((d) => d.Route),
  )
const JouleHomeCurrentSystemLazyRoute =
  JouleHomeCurrentSystemLazyRouteImport.update({
    id: '/current-system',
    path: '/current-system',
    getParentRoute: () => JouleHomeLazyRoute,
  } as any).lazy(() =>
    import('./routes/joule-home/current-system.lazy').then((d) => d.Route),
  )
const JouleHomeAnalysisLazyRoute = JouleHomeAnalysisLazyRouteImport.update({
  id: '/analysis',
  path: '/analysis',
  getParentRoute: () => JouleHomeLazyRoute,
} as any).lazy(() =>
  import('./routes/joule-home/analysis.lazy').then((d) => d.Route),
)
const FlowHomeUsageLazyRoute = FlowHomeUsageLazyRouteImport.update({
  id: '/usage',
  path: '/usage',
  getParentRoute: () => FlowHomeLazyRoute,
} as any).lazy(() =>
  import('./routes/flow-home/usage.lazy').then((d) => d.Route),
)
const FlowHomeProfileLazyRoute = FlowHomeProfileLazyRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => FlowHomeLazyRoute,
} as any).lazy(() =>
  import('./routes/flow-home/profile.lazy').then((d) => d.Route),
)
const FlowHomeCostScheduleLazyRoute =
  FlowHomeCostScheduleLazyRouteImport.update({
    id: '/cost-schedule',
    path: '/cost-schedule',
    getParentRoute: () => FlowHomeLazyRoute,
  } as any).lazy(() =>
    import('./routes/flow-home/cost-schedule.lazy').then((d) => d.Route),
  )

export interface FileRoutesByFullPath {
  '/': typeof IndexLazyRoute
  '/biology': typeof BiologyLazyRoute
  '/flow-home': typeof FlowHomeLazyRouteWithChildren
  '/joule-home': typeof JouleHomeLazyRouteWithChildren
  '/photography': typeof PhotographyLazyRoute
  '/flow-home/cost-schedule': typeof FlowHomeCostScheduleLazyRoute
  '/flow-home/profile': typeof FlowHomeProfileLazyRoute
  '/flow-home/usage': typeof FlowHomeUsageLazyRoute
  '/joule-home/analysis': typeof JouleHomeAnalysisLazyRoute
  '/joule-home/current-system': typeof JouleHomeCurrentSystemLazyRoute
  '/joule-home/energy-usage-form': typeof JouleHomeEnergyUsageFormLazyRoute
  '/flow-home/': typeof FlowHomeIndexLazyRoute
  '/joule-home/': typeof JouleHomeIndexLazyRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexLazyRoute
  '/biology': typeof BiologyLazyRoute
  '/photography': typeof PhotographyLazyRoute
  '/flow-home/cost-schedule': typeof FlowHomeCostScheduleLazyRoute
  '/flow-home/profile': typeof FlowHomeProfileLazyRoute
  '/flow-home/usage': typeof FlowHomeUsageLazyRoute
  '/joule-home/analysis': typeof JouleHomeAnalysisLazyRoute
  '/joule-home/current-system': typeof JouleHomeCurrentSystemLazyRoute
  '/joule-home/energy-usage-form': typeof JouleHomeEnergyUsageFormLazyRoute
  '/flow-home': typeof FlowHomeIndexLazyRoute
  '/joule-home': typeof JouleHomeIndexLazyRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexLazyRoute
  '/biology': typeof BiologyLazyRoute
  '/flow-home': typeof FlowHomeLazyRouteWithChildren
  '/joule-home': typeof JouleHomeLazyRouteWithChildren
  '/photography': typeof PhotographyLazyRoute
  '/flow-home/cost-schedule': typeof FlowHomeCostScheduleLazyRoute
  '/flow-home/profile': typeof FlowHomeProfileLazyRoute
  '/flow-home/usage': typeof FlowHomeUsageLazyRoute
  '/joule-home/analysis': typeof JouleHomeAnalysisLazyRoute
  '/joule-home/current-system': typeof JouleHomeCurrentSystemLazyRoute
  '/joule-home/energy-usage-form': typeof JouleHomeEnergyUsageFormLazyRoute
  '/flow-home/': typeof FlowHomeIndexLazyRoute
  '/joule-home/': typeof JouleHomeIndexLazyRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/biology'
    | '/flow-home'
    | '/joule-home'
    | '/photography'
    | '/flow-home/cost-schedule'
    | '/flow-home/profile'
    | '/flow-home/usage'
    | '/joule-home/analysis'
    | '/joule-home/current-system'
    | '/joule-home/energy-usage-form'
    | '/flow-home/'
    | '/joule-home/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/biology'
    | '/photography'
    | '/flow-home/cost-schedule'
    | '/flow-home/profile'
    | '/flow-home/usage'
    | '/joule-home/analysis'
    | '/joule-home/current-system'
    | '/joule-home/energy-usage-form'
    | '/flow-home'
    | '/joule-home'
  id:
    | '__root__'
    | '/'
    | '/biology'
    | '/flow-home'
    | '/joule-home'
    | '/photography'
    | '/flow-home/cost-schedule'
    | '/flow-home/profile'
    | '/flow-home/usage'
    | '/joule-home/analysis'
    | '/joule-home/current-system'
    | '/joule-home/energy-usage-form'
    | '/flow-home/'
    | '/joule-home/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexLazyRoute: typeof IndexLazyRoute
  BiologyLazyRoute: typeof BiologyLazyRoute
  FlowHomeLazyRoute: typeof FlowHomeLazyRouteWithChildren
  JouleHomeLazyRoute: typeof JouleHomeLazyRouteWithChildren
  PhotographyLazyRoute: typeof PhotographyLazyRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/photography': {
      id: '/photography'
      path: '/photography'
      fullPath: '/photography'
      preLoaderRoute: typeof PhotographyLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/joule-home': {
      id: '/joule-home'
      path: '/joule-home'
      fullPath: '/joule-home'
      preLoaderRoute: typeof JouleHomeLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/flow-home': {
      id: '/flow-home'
      path: '/flow-home'
      fullPath: '/flow-home'
      preLoaderRoute: typeof FlowHomeLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/biology': {
      id: '/biology'
      path: '/biology'
      fullPath: '/biology'
      preLoaderRoute: typeof BiologyLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/joule-home/': {
      id: '/joule-home/'
      path: '/'
      fullPath: '/joule-home/'
      preLoaderRoute: typeof JouleHomeIndexLazyRouteImport
      parentRoute: typeof JouleHomeLazyRoute
    }
    '/flow-home/': {
      id: '/flow-home/'
      path: '/'
      fullPath: '/flow-home/'
      preLoaderRoute: typeof FlowHomeIndexLazyRouteImport
      parentRoute: typeof FlowHomeLazyRoute
    }
    '/joule-home/energy-usage-form': {
      id: '/joule-home/energy-usage-form'
      path: '/energy-usage-form'
      fullPath: '/joule-home/energy-usage-form'
      preLoaderRoute: typeof JouleHomeEnergyUsageFormLazyRouteImport
      parentRoute: typeof JouleHomeLazyRoute
    }
    '/joule-home/current-system': {
      id: '/joule-home/current-system'
      path: '/current-system'
      fullPath: '/joule-home/current-system'
      preLoaderRoute: typeof JouleHomeCurrentSystemLazyRouteImport
      parentRoute: typeof JouleHomeLazyRoute
    }
    '/joule-home/analysis': {
      id: '/joule-home/analysis'
      path: '/analysis'
      fullPath: '/joule-home/analysis'
      preLoaderRoute: typeof JouleHomeAnalysisLazyRouteImport
      parentRoute: typeof JouleHomeLazyRoute
    }
    '/flow-home/usage': {
      id: '/flow-home/usage'
      path: '/usage'
      fullPath: '/flow-home/usage'
      preLoaderRoute: typeof FlowHomeUsageLazyRouteImport
      parentRoute: typeof FlowHomeLazyRoute
    }
    '/flow-home/profile': {
      id: '/flow-home/profile'
      path: '/profile'
      fullPath: '/flow-home/profile'
      preLoaderRoute: typeof FlowHomeProfileLazyRouteImport
      parentRoute: typeof FlowHomeLazyRoute
    }
    '/flow-home/cost-schedule': {
      id: '/flow-home/cost-schedule'
      path: '/cost-schedule'
      fullPath: '/flow-home/cost-schedule'
      preLoaderRoute: typeof FlowHomeCostScheduleLazyRouteImport
      parentRoute: typeof FlowHomeLazyRoute
    }
  }
}

interface FlowHomeLazyRouteChildren {
  FlowHomeCostScheduleLazyRoute: typeof FlowHomeCostScheduleLazyRoute
  FlowHomeProfileLazyRoute: typeof FlowHomeProfileLazyRoute
  FlowHomeUsageLazyRoute: typeof FlowHomeUsageLazyRoute
  FlowHomeIndexLazyRoute: typeof FlowHomeIndexLazyRoute
}

const FlowHomeLazyRouteChildren: FlowHomeLazyRouteChildren = {
  FlowHomeCostScheduleLazyRoute: FlowHomeCostScheduleLazyRoute,
  FlowHomeProfileLazyRoute: FlowHomeProfileLazyRoute,
  FlowHomeUsageLazyRoute: FlowHomeUsageLazyRoute,
  FlowHomeIndexLazyRoute: FlowHomeIndexLazyRoute,
}

const FlowHomeLazyRouteWithChildren = FlowHomeLazyRoute._addFileChildren(
  FlowHomeLazyRouteChildren,
)

interface JouleHomeLazyRouteChildren {
  JouleHomeAnalysisLazyRoute: typeof JouleHomeAnalysisLazyRoute
  JouleHomeCurrentSystemLazyRoute: typeof JouleHomeCurrentSystemLazyRoute
  JouleHomeEnergyUsageFormLazyRoute: typeof JouleHomeEnergyUsageFormLazyRoute
  JouleHomeIndexLazyRoute: typeof JouleHomeIndexLazyRoute
}

const JouleHomeLazyRouteChildren: JouleHomeLazyRouteChildren = {
  JouleHomeAnalysisLazyRoute: JouleHomeAnalysisLazyRoute,
  JouleHomeCurrentSystemLazyRoute: JouleHomeCurrentSystemLazyRoute,
  JouleHomeEnergyUsageFormLazyRoute: JouleHomeEnergyUsageFormLazyRoute,
  JouleHomeIndexLazyRoute: JouleHomeIndexLazyRoute,
}

const JouleHomeLazyRouteWithChildren = JouleHomeLazyRoute._addFileChildren(
  JouleHomeLazyRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexLazyRoute: IndexLazyRoute,
  BiologyLazyRoute: BiologyLazyRoute,
  FlowHomeLazyRoute: FlowHomeLazyRouteWithChildren,
  JouleHomeLazyRoute: JouleHomeLazyRouteWithChildren,
  PhotographyLazyRoute: PhotographyLazyRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
