/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'

// Create Virtual Routes

const PhotographyLazyImport = createFileRoute('/photography')()
const JouleHomeLazyImport = createFileRoute('/joule-home')()
const BiologyLazyImport = createFileRoute('/biology')()
const IndexLazyImport = createFileRoute('/')()
const JouleHomeIndexLazyImport = createFileRoute('/joule-home/')()
const JouleHomeEnergyUsageFormLazyImport = createFileRoute(
  '/joule-home/energy-usage-form',
)()
const JouleHomeEnergyUsageAnalysisLazyImport = createFileRoute(
  '/joule-home/energy-usage-analysis',
)()
const JouleHomeCurrentSystemLazyImport = createFileRoute(
  '/joule-home/current-system',
)()

// Create/Update Routes

const PhotographyLazyRoute = PhotographyLazyImport.update({
  id: '/photography',
  path: '/photography',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/photography.lazy').then((d) => d.Route))

const JouleHomeLazyRoute = JouleHomeLazyImport.update({
  id: '/joule-home',
  path: '/joule-home',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/joule-home.lazy').then((d) => d.Route))

const BiologyLazyRoute = BiologyLazyImport.update({
  id: '/biology',
  path: '/biology',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/biology.lazy').then((d) => d.Route))

const IndexLazyRoute = IndexLazyImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/index.lazy').then((d) => d.Route))

const JouleHomeIndexLazyRoute = JouleHomeIndexLazyImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => JouleHomeLazyRoute,
} as any).lazy(() =>
  import('./routes/joule-home/index.lazy').then((d) => d.Route),
)

const JouleHomeEnergyUsageFormLazyRoute =
  JouleHomeEnergyUsageFormLazyImport.update({
    id: '/energy-usage-form',
    path: '/energy-usage-form',
    getParentRoute: () => JouleHomeLazyRoute,
  } as any).lazy(() =>
    import('./routes/joule-home/energy-usage-form.lazy').then((d) => d.Route),
  )

const JouleHomeEnergyUsageAnalysisLazyRoute =
  JouleHomeEnergyUsageAnalysisLazyImport.update({
    id: '/energy-usage-analysis',
    path: '/energy-usage-analysis',
    getParentRoute: () => JouleHomeLazyRoute,
  } as any).lazy(() =>
    import('./routes/joule-home/energy-usage-analysis.lazy').then(
      (d) => d.Route,
    ),
  )

const JouleHomeCurrentSystemLazyRoute = JouleHomeCurrentSystemLazyImport.update(
  {
    id: '/current-system',
    path: '/current-system',
    getParentRoute: () => JouleHomeLazyRoute,
  } as any,
).lazy(() =>
  import('./routes/joule-home/current-system.lazy').then((d) => d.Route),
)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexLazyImport
      parentRoute: typeof rootRoute
    }
    '/biology': {
      id: '/biology'
      path: '/biology'
      fullPath: '/biology'
      preLoaderRoute: typeof BiologyLazyImport
      parentRoute: typeof rootRoute
    }
    '/joule-home': {
      id: '/joule-home'
      path: '/joule-home'
      fullPath: '/joule-home'
      preLoaderRoute: typeof JouleHomeLazyImport
      parentRoute: typeof rootRoute
    }
    '/photography': {
      id: '/photography'
      path: '/photography'
      fullPath: '/photography'
      preLoaderRoute: typeof PhotographyLazyImport
      parentRoute: typeof rootRoute
    }
    '/joule-home/current-system': {
      id: '/joule-home/current-system'
      path: '/current-system'
      fullPath: '/joule-home/current-system'
      preLoaderRoute: typeof JouleHomeCurrentSystemLazyImport
      parentRoute: typeof JouleHomeLazyImport
    }
    '/joule-home/energy-usage-analysis': {
      id: '/joule-home/energy-usage-analysis'
      path: '/energy-usage-analysis'
      fullPath: '/joule-home/energy-usage-analysis'
      preLoaderRoute: typeof JouleHomeEnergyUsageAnalysisLazyImport
      parentRoute: typeof JouleHomeLazyImport
    }
    '/joule-home/energy-usage-form': {
      id: '/joule-home/energy-usage-form'
      path: '/energy-usage-form'
      fullPath: '/joule-home/energy-usage-form'
      preLoaderRoute: typeof JouleHomeEnergyUsageFormLazyImport
      parentRoute: typeof JouleHomeLazyImport
    }
    '/joule-home/': {
      id: '/joule-home/'
      path: '/'
      fullPath: '/joule-home/'
      preLoaderRoute: typeof JouleHomeIndexLazyImport
      parentRoute: typeof JouleHomeLazyImport
    }
  }
}

// Create and export the route tree

interface JouleHomeLazyRouteChildren {
  JouleHomeCurrentSystemLazyRoute: typeof JouleHomeCurrentSystemLazyRoute
  JouleHomeEnergyUsageAnalysisLazyRoute: typeof JouleHomeEnergyUsageAnalysisLazyRoute
  JouleHomeEnergyUsageFormLazyRoute: typeof JouleHomeEnergyUsageFormLazyRoute
  JouleHomeIndexLazyRoute: typeof JouleHomeIndexLazyRoute
}

const JouleHomeLazyRouteChildren: JouleHomeLazyRouteChildren = {
  JouleHomeCurrentSystemLazyRoute: JouleHomeCurrentSystemLazyRoute,
  JouleHomeEnergyUsageAnalysisLazyRoute: JouleHomeEnergyUsageAnalysisLazyRoute,
  JouleHomeEnergyUsageFormLazyRoute: JouleHomeEnergyUsageFormLazyRoute,
  JouleHomeIndexLazyRoute: JouleHomeIndexLazyRoute,
}

const JouleHomeLazyRouteWithChildren = JouleHomeLazyRoute._addFileChildren(
  JouleHomeLazyRouteChildren,
)

export interface FileRoutesByFullPath {
  '/': typeof IndexLazyRoute
  '/biology': typeof BiologyLazyRoute
  '/joule-home': typeof JouleHomeLazyRouteWithChildren
  '/photography': typeof PhotographyLazyRoute
  '/joule-home/current-system': typeof JouleHomeCurrentSystemLazyRoute
  '/joule-home/energy-usage-analysis': typeof JouleHomeEnergyUsageAnalysisLazyRoute
  '/joule-home/energy-usage-form': typeof JouleHomeEnergyUsageFormLazyRoute
  '/joule-home/': typeof JouleHomeIndexLazyRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexLazyRoute
  '/biology': typeof BiologyLazyRoute
  '/photography': typeof PhotographyLazyRoute
  '/joule-home/current-system': typeof JouleHomeCurrentSystemLazyRoute
  '/joule-home/energy-usage-analysis': typeof JouleHomeEnergyUsageAnalysisLazyRoute
  '/joule-home/energy-usage-form': typeof JouleHomeEnergyUsageFormLazyRoute
  '/joule-home': typeof JouleHomeIndexLazyRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexLazyRoute
  '/biology': typeof BiologyLazyRoute
  '/joule-home': typeof JouleHomeLazyRouteWithChildren
  '/photography': typeof PhotographyLazyRoute
  '/joule-home/current-system': typeof JouleHomeCurrentSystemLazyRoute
  '/joule-home/energy-usage-analysis': typeof JouleHomeEnergyUsageAnalysisLazyRoute
  '/joule-home/energy-usage-form': typeof JouleHomeEnergyUsageFormLazyRoute
  '/joule-home/': typeof JouleHomeIndexLazyRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/biology'
    | '/joule-home'
    | '/photography'
    | '/joule-home/current-system'
    | '/joule-home/energy-usage-analysis'
    | '/joule-home/energy-usage-form'
    | '/joule-home/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/biology'
    | '/photography'
    | '/joule-home/current-system'
    | '/joule-home/energy-usage-analysis'
    | '/joule-home/energy-usage-form'
    | '/joule-home'
  id:
    | '__root__'
    | '/'
    | '/biology'
    | '/joule-home'
    | '/photography'
    | '/joule-home/current-system'
    | '/joule-home/energy-usage-analysis'
    | '/joule-home/energy-usage-form'
    | '/joule-home/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexLazyRoute: typeof IndexLazyRoute
  BiologyLazyRoute: typeof BiologyLazyRoute
  JouleHomeLazyRoute: typeof JouleHomeLazyRouteWithChildren
  PhotographyLazyRoute: typeof PhotographyLazyRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexLazyRoute: IndexLazyRoute,
  BiologyLazyRoute: BiologyLazyRoute,
  JouleHomeLazyRoute: JouleHomeLazyRouteWithChildren,
  PhotographyLazyRoute: PhotographyLazyRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/biology",
        "/joule-home",
        "/photography"
      ]
    },
    "/": {
      "filePath": "index.lazy.tsx"
    },
    "/biology": {
      "filePath": "biology.lazy.tsx"
    },
    "/joule-home": {
      "filePath": "joule-home.lazy.tsx",
      "children": [
        "/joule-home/current-system",
        "/joule-home/energy-usage-analysis",
        "/joule-home/energy-usage-form",
        "/joule-home/"
      ]
    },
    "/photography": {
      "filePath": "photography.lazy.tsx"
    },
    "/joule-home/current-system": {
      "filePath": "joule-home/current-system.lazy.tsx",
      "parent": "/joule-home"
    },
    "/joule-home/energy-usage-analysis": {
      "filePath": "joule-home/energy-usage-analysis.lazy.tsx",
      "parent": "/joule-home"
    },
    "/joule-home/energy-usage-form": {
      "filePath": "joule-home/energy-usage-form.lazy.tsx",
      "parent": "/joule-home"
    },
    "/joule-home/": {
      "filePath": "joule-home/index.lazy.tsx",
      "parent": "/joule-home"
    }
  }
}
ROUTE_MANIFEST_END */
